export const ROUTES = {
  login: '/login',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password/:token',
  mfa: '/mfa',
  selectTenant: '/select-tenant',
  unauthorized: '/unauthorized',
  sessionExpired: '/session-expired',

  dashboard: '/dashboard',
  attendance: '/attendance',
  attendanceDetail: '/attendance/:userId',
  maps: '/maps',
  heatmap: '/maps/heatmap',
  incidents: '/incidents',
  incidentNew: '/incidents/new',
  incidentDetail: '/incidents/:id',
  notifications: '/notifications',
  imports: '/imports',
  importUpload: '/imports/upload',
  importDetail: '/imports/:id',
  importTemplates: '/import-templates',
  importTemplateNew: '/import-templates/new',
  importTemplateDetail: '/import-templates/:id',
  reports: '/reports',
  reportDetail: '/reports/:reportType',
  audit: '/audit',
  auditDetail: '/audit/:id',
  operations: '/operations',
  operationsPlantNew: '/operations/plants/new',
  operationsPlantEdit: '/operations/plants/:id/edit',
  operationsSiteNew: '/operations/sites/new',
  operationsSiteEdit: '/operations/sites/:id/edit',
  operationsRouteNew: '/operations/routes/new',
  operationsRouteEdit: '/operations/routes/:id/edit',
  settings: '/settings',
} as const

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES]
