// Auto-generated by scripts/generate-territory-catalog.py — do not edit manually.

export interface TerritoryDepartment {
  id: string
  label: string
  departmentKey: string
  countryCode: string
}

export interface TerritoryMunicipality {
  id: string
  label: string
  municipalityKey: string
  departmentKey: string
  departmentLabel: string
  countryCode: string
  latitude: number
  longitude: number
}

export interface TerritoryProject {
  id: string
  label: string
  noProyect: string
  countryCode: string
  latitude: number
  longitude: number
  departmentKeys: string[]
}

export const TERRITORY_DEPARTMENTS: TerritoryDepartment[] = [
  {
    "id": "dept-antioquia",
    "label": "Antioquia",
    "departmentKey": "antioquia",
    "countryCode": "CO"
  },
  {
    "id": "dept-arauca",
    "label": "Arauca",
    "departmentKey": "arauca",
    "countryCode": "CO"
  },
  {
    "id": "dept-atlantico",
    "label": "Atlántico",
    "departmentKey": "atlantico",
    "countryCode": "CO"
  },
  {
    "id": "dept-bolivar",
    "label": "Bolívar",
    "departmentKey": "bolivar",
    "countryCode": "CO"
  },
  {
    "id": "dept-boyaca",
    "label": "Boyacá",
    "departmentKey": "boyaca",
    "countryCode": "CO"
  },
  {
    "id": "dept-caldas",
    "label": "Caldas",
    "departmentKey": "caldas",
    "countryCode": "CO"
  },
  {
    "id": "dept-caqueta",
    "label": "Caquetá",
    "departmentKey": "caqueta",
    "countryCode": "CO"
  },
  {
    "id": "dept-casanare",
    "label": "Casanare",
    "departmentKey": "casanare",
    "countryCode": "CO"
  },
  {
    "id": "dept-cauca",
    "label": "Cauca",
    "departmentKey": "cauca",
    "countryCode": "CO"
  },
  {
    "id": "dept-cesar",
    "label": "Cesar",
    "departmentKey": "cesar",
    "countryCode": "CO"
  },
  {
    "id": "dept-choco",
    "label": "Chocó",
    "departmentKey": "choco",
    "countryCode": "CO"
  },
  {
    "id": "dept-cundinamarca",
    "label": "Cundinamarca",
    "departmentKey": "cundinamarca",
    "countryCode": "CO"
  },
  {
    "id": "dept-cordoba",
    "label": "Córdoba",
    "departmentKey": "cordoba",
    "countryCode": "CO"
  },
  {
    "id": "dept-guaviare",
    "label": "Guaviare",
    "departmentKey": "guaviare",
    "countryCode": "CO"
  },
  {
    "id": "dept-huila",
    "label": "Huila",
    "departmentKey": "huila",
    "countryCode": "CO"
  },
  {
    "id": "dept-la-guajira",
    "label": "La Guajira",
    "departmentKey": "la guajira",
    "countryCode": "CO"
  },
  {
    "id": "dept-magdalena",
    "label": "Magdalena",
    "departmentKey": "magdalena",
    "countryCode": "CO"
  },
  {
    "id": "dept-meta",
    "label": "Meta",
    "departmentKey": "meta",
    "countryCode": "CO"
  },
  {
    "id": "dept-narino",
    "label": "Nariño",
    "departmentKey": "narino",
    "countryCode": "CO"
  },
  {
    "id": "dept-norte-de-santander",
    "label": "Norte de Santander",
    "departmentKey": "norte de santander",
    "countryCode": "CO"
  },
  {
    "id": "dept-putumayo",
    "label": "Putumayo",
    "departmentKey": "putumayo",
    "countryCode": "CO"
  },
  {
    "id": "dept-quindio",
    "label": "Quindío",
    "departmentKey": "quindio",
    "countryCode": "CO"
  },
  {
    "id": "dept-risaralda",
    "label": "Risaralda",
    "departmentKey": "risaralda",
    "countryCode": "CO"
  },
  {
    "id": "dept-santander",
    "label": "Santander",
    "departmentKey": "santander",
    "countryCode": "CO"
  },
  {
    "id": "dept-tolima",
    "label": "Tolima",
    "departmentKey": "tolima",
    "countryCode": "CO"
  },
  {
    "id": "dept-valle-del-cauca",
    "label": "Valle del Cauca",
    "departmentKey": "valle del cauca",
    "countryCode": "CO"
  },
  {
    "id": "dept-nan",
    "label": "nan",
    "departmentKey": "nan",
    "countryCode": "CO"
  }
]

export const TERRITORY_MUNICIPALITIES: TerritoryMunicipality[] = [
  {
    "id": "muni-angosturas",
    "label": "Angosturas",
    "municipalityKey": "angosturas",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-anori",
    "label": "Anorí",
    "municipalityKey": "anori",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-bello",
    "label": "Bello",
    "municipalityKey": "bello",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-briceno",
    "label": "Briceño",
    "municipalityKey": "briceno",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-carolina-del-principe",
    "label": "Carolina del Principe",
    "municipalityKey": "carolina del principe",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-caucasia",
    "label": "Caucasia",
    "municipalityKey": "caucasia",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-copacabana",
    "label": "Copacabana",
    "municipalityKey": "copacabana",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-caceres",
    "label": "Cáceres",
    "municipalityKey": "caceres",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-dabeiba",
    "label": "Dabeiba",
    "municipalityKey": "dabeiba",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-ituango",
    "label": "Ituango",
    "municipalityKey": "ituango",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-medellin",
    "label": "Medellín",
    "municipalityKey": "medellin",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-mutata",
    "label": "Mutatá",
    "municipalityKey": "mutata",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-narino",
    "label": "Nariño",
    "municipalityKey": "narino",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-nechi",
    "label": "Nechí",
    "municipalityKey": "nechi",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-salgar",
    "label": "Salgar",
    "municipalityKey": "salgar",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-san-andres-de-cuerquia",
    "label": "San Andrés de Cuerquia",
    "municipalityKey": "san andres de cuerquia",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-san-roque",
    "label": "San Roque",
    "municipalityKey": "san roque",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-santafe-de-antioquia",
    "label": "Santafé de Antioquia",
    "municipalityKey": "santafe de antioquia",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-segovia",
    "label": "Segovia",
    "municipalityKey": "segovia",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-sonson",
    "label": "Sonsón",
    "municipalityKey": "sonson",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-taraza",
    "label": "Tarazá",
    "municipalityKey": "taraza",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-toledo",
    "label": "Toledo",
    "municipalityKey": "toledo",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-tamesis",
    "label": "Támesis",
    "municipalityKey": "tamesis",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-urrao",
    "label": "Urrao",
    "municipalityKey": "urrao",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-valdivia",
    "label": "Valdivia",
    "municipalityKey": "valdivia",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-vegachi",
    "label": "Vegachí",
    "municipalityKey": "vegachi",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-versalles",
    "label": "Versalles",
    "municipalityKey": "versalles",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-yarumal",
    "label": "Yarumal",
    "municipalityKey": "yarumal",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-yondo",
    "label": "Yondó",
    "municipalityKey": "yondo",
    "departmentKey": "antioquia",
    "departmentLabel": "Antioquia",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-arauca",
    "label": "Arauca",
    "municipalityKey": "arauca",
    "departmentKey": "arauca",
    "departmentLabel": "Arauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-arauquita",
    "label": "Arauquita",
    "municipalityKey": "arauquita",
    "departmentKey": "arauca",
    "departmentLabel": "Arauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-fortul",
    "label": "Fortul",
    "municipalityKey": "fortul",
    "departmentKey": "arauca",
    "departmentLabel": "Arauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-puerto-rondon",
    "label": "Puerto Rondón",
    "municipalityKey": "puerto rondon",
    "departmentKey": "arauca",
    "departmentLabel": "Arauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-saravena",
    "label": "Saravena",
    "municipalityKey": "saravena",
    "departmentKey": "arauca",
    "departmentLabel": "Arauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-tame",
    "label": "Tame",
    "municipalityKey": "tame",
    "departmentKey": "arauca",
    "departmentLabel": "Arauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-nan",
    "label": "nan",
    "municipalityKey": "nan",
    "departmentKey": "arauca",
    "departmentLabel": "Arauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-sabanalarga",
    "label": "Sabanalarga",
    "municipalityKey": "sabanalarga",
    "departmentKey": "atlantico",
    "departmentLabel": "Atlántico",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-carmen-de-bolivar",
    "label": "Carmen de Bolivar",
    "municipalityKey": "carmen de bolivar",
    "departmentKey": "bolivar",
    "departmentLabel": "Bolívar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-santa-rosa-del-sur",
    "label": "Santa Rosa del Sur",
    "municipalityKey": "santa rosa del sur",
    "departmentKey": "bolivar",
    "departmentLabel": "Bolívar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-sogamoso",
    "label": "Sogamoso",
    "municipalityKey": "sogamoso",
    "departmentKey": "boyaca",
    "departmentLabel": "Boyacá",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-tunja",
    "label": "Tunja",
    "municipalityKey": "tunja",
    "departmentKey": "boyaca",
    "departmentLabel": "Boyacá",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-marquetalia",
    "label": "Marquetalia",
    "municipalityKey": "marquetalia",
    "departmentKey": "caldas",
    "departmentLabel": "Caldas",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-cartagena-del-chaira",
    "label": "Cartagena del Chairá",
    "municipalityKey": "cartagena del chaira",
    "departmentKey": "caqueta",
    "departmentLabel": "Caquetá",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-florencia",
    "label": "Florencia",
    "municipalityKey": "florencia",
    "departmentKey": "caqueta",
    "departmentLabel": "Caquetá",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-yopal",
    "label": "Yopal",
    "municipalityKey": "yopal",
    "departmentKey": "casanare",
    "departmentLabel": "Casanare",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-argelia",
    "label": "Argelia",
    "municipalityKey": "argelia",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-balboa",
    "label": "Balboa",
    "municipalityKey": "balboa",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-buenos-aires",
    "label": "Buenos Aires",
    "municipalityKey": "buenos aires",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-cajibio",
    "label": "Cajibío",
    "municipalityKey": "cajibio",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-caloto",
    "label": "Caloto",
    "municipalityKey": "caloto",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-corinto",
    "label": "Corinto",
    "municipalityKey": "corinto",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-bordo",
    "label": "El Bordo",
    "municipalityKey": "el bordo",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-tambo",
    "label": "El Tambo",
    "municipalityKey": "el tambo",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-lopez-de-micay",
    "label": "López de Micay",
    "municipalityKey": "lopez de micay",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-miranda",
    "label": "Miranda",
    "municipalityKey": "miranda",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-morales",
    "label": "Morales",
    "municipalityKey": "morales",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-padilla",
    "label": "Padilla",
    "municipalityKey": "padilla",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-patia",
    "label": "Patía",
    "municipalityKey": "patia",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-popayan",
    "label": "Popayán",
    "municipalityKey": "popayan",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-puerto-tejada",
    "label": "Puerto Tejada",
    "municipalityKey": "puerto tejada",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-rosas",
    "label": "Rosas",
    "municipalityKey": "rosas",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-santander-de-quilichao",
    "label": "Santander de Quilichao",
    "municipalityKey": "santander de quilichao",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-silvia",
    "label": "Silvia",
    "municipalityKey": "silvia",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-sucre",
    "label": "Sucre",
    "municipalityKey": "sucre",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-suarez",
    "label": "Suárez",
    "municipalityKey": "suarez",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-tambo",
    "label": "Tambo",
    "municipalityKey": "tambo",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-timbio",
    "label": "Timbío",
    "municipalityKey": "timbio",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-toribio",
    "label": "Toribío",
    "municipalityKey": "toribio",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-totoro",
    "label": "Totoró",
    "municipalityKey": "totoro",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-villa-rica",
    "label": "Villa Rica",
    "municipalityKey": "villa rica",
    "departmentKey": "cauca",
    "departmentLabel": "Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-aguachica",
    "label": "Aguachica",
    "municipalityKey": "aguachica",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-becerril",
    "label": "Becerril",
    "municipalityKey": "becerril",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-curumani",
    "label": "Curumaní",
    "municipalityKey": "curumani",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-la-gloria",
    "label": "La Gloria",
    "municipalityKey": "la gloria",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-la-jagua",
    "label": "La Jagua",
    "municipalityKey": "la jagua",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-la-jagua-de-ibirico",
    "label": "La Jagua de Ibirico",
    "municipalityKey": "la jagua de ibirico",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-pailitas",
    "label": "Pailitas",
    "municipalityKey": "pailitas",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-pelaya",
    "label": "Pelaya",
    "municipalityKey": "pelaya",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-san-martin",
    "label": "San Martin",
    "municipalityKey": "san martin",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-san-roque",
    "label": "San Roque",
    "municipalityKey": "san roque",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-valledupar",
    "label": "Valledupar",
    "municipalityKey": "valledupar",
    "departmentKey": "cesar",
    "departmentLabel": "Cesar",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-santa-rita-de-iro",
    "label": "Santa Rita de Iró",
    "municipalityKey": "santa rita de iro",
    "departmentKey": "choco",
    "departmentLabel": "Chocó",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-tado",
    "label": "Tadó",
    "municipalityKey": "tado",
    "departmentKey": "choco",
    "departmentLabel": "Chocó",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-montelibano",
    "label": "Montelíbano",
    "municipalityKey": "montelibano",
    "departmentKey": "cordoba",
    "departmentLabel": "Córdoba",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-bogota",
    "label": "Bogotá",
    "municipalityKey": "bogota",
    "departmentKey": "cundinamarca",
    "departmentLabel": "Cundinamarca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-la-calera",
    "label": "La Calera",
    "municipalityKey": "la calera",
    "departmentKey": "cundinamarca",
    "departmentLabel": "Cundinamarca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-usme-bogota",
    "label": "Usme (Bogotá)",
    "municipalityKey": "usme bogota",
    "departmentKey": "cundinamarca",
    "departmentLabel": "Cundinamarca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-calamar",
    "label": "Calamar",
    "municipalityKey": "calamar",
    "departmentKey": "guaviare",
    "departmentLabel": "Guaviare",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-retorno",
    "label": "El  Retorno",
    "municipalityKey": "el retorno",
    "departmentKey": "guaviare",
    "departmentLabel": "Guaviare",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-san-jose-del-guaviare",
    "label": "San José del Guaviare",
    "municipalityKey": "san jose del guaviare",
    "departmentKey": "guaviare",
    "departmentLabel": "Guaviare",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-hobo",
    "label": "Hobo",
    "municipalityKey": "hobo",
    "departmentKey": "huila",
    "departmentLabel": "Huila",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-la-plata",
    "label": "La Plata",
    "municipalityKey": "la plata",
    "departmentKey": "huila",
    "departmentLabel": "Huila",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-neiva",
    "label": "Neiva",
    "municipalityKey": "neiva",
    "departmentKey": "huila",
    "departmentLabel": "Huila",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-palestina",
    "label": "Palestina",
    "municipalityKey": "palestina",
    "departmentKey": "huila",
    "departmentLabel": "Huila",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-amalfi",
    "label": "Amalfi",
    "municipalityKey": "amalfi",
    "departmentKey": "la guajira",
    "departmentLabel": "La Guajira",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-barrancas",
    "label": "Barrancas",
    "municipalityKey": "barrancas",
    "departmentKey": "la guajira",
    "departmentLabel": "La Guajira",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-maicao",
    "label": "Maicao",
    "municipalityKey": "maicao",
    "departmentKey": "la guajira",
    "departmentLabel": "La Guajira",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-manaure",
    "label": "Manaure",
    "municipalityKey": "manaure",
    "departmentKey": "la guajira",
    "departmentLabel": "La Guajira",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-nazareth",
    "label": "Nazareth",
    "municipalityKey": "nazareth",
    "departmentKey": "la guajira",
    "departmentLabel": "La Guajira",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-riohacha",
    "label": "Riohacha",
    "municipalityKey": "riohacha",
    "departmentKey": "la guajira",
    "departmentLabel": "La Guajira",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-uribia",
    "label": "Uribia",
    "municipalityKey": "uribia",
    "departmentKey": "la guajira",
    "departmentLabel": "La Guajira",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-aracataca",
    "label": "Aracataca",
    "municipalityKey": "aracataca",
    "departmentKey": "magdalena",
    "departmentLabel": "Magdalena",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-cienaga",
    "label": "Ciénaga",
    "municipalityKey": "cienaga",
    "departmentKey": "magdalena",
    "departmentLabel": "Magdalena",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-fundacion",
    "label": "Fundacion",
    "municipalityKey": "fundacion",
    "departmentKey": "magdalena",
    "departmentLabel": "Magdalena",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-sabana-grande",
    "label": "Sabana Grande",
    "municipalityKey": "sabana grande",
    "departmentKey": "magdalena",
    "departmentLabel": "Magdalena",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-santa-marta",
    "label": "Santa Marta",
    "municipalityKey": "santa marta",
    "departmentKey": "magdalena",
    "departmentLabel": "Magdalena",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-granada",
    "label": "Granada",
    "municipalityKey": "granada",
    "departmentKey": "meta",
    "departmentLabel": "Meta",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-la-macarena",
    "label": "La Macarena",
    "municipalityKey": "la macarena",
    "departmentKey": "meta",
    "departmentLabel": "Meta",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-vista-hermosa",
    "label": "Vista Hermosa",
    "municipalityKey": "vista hermosa",
    "departmentKey": "meta",
    "departmentLabel": "Meta",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-nan",
    "label": "nan",
    "municipalityKey": "nan",
    "departmentKey": "nan",
    "departmentLabel": "nan",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-barbacoas",
    "label": "Barbacoas",
    "municipalityKey": "barbacoas",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-charco",
    "label": "El Charco",
    "municipalityKey": "el charco",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-ipiales",
    "label": "Ipiales",
    "municipalityKey": "ipiales",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-olaya-herrera",
    "label": "Olaya Herrera",
    "municipalityKey": "olaya herrera",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-pasto",
    "label": "Pasto",
    "municipalityKey": "pasto",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-policarpa",
    "label": "Policarpa",
    "municipalityKey": "policarpa",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-samaniego",
    "label": "Samaniego",
    "municipalityKey": "samaniego",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-tumaco",
    "label": "Tumaco",
    "municipalityKey": "tumaco",
    "departmentKey": "narino",
    "departmentLabel": "Nariño",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-chinacota",
    "label": "Chinácota",
    "municipalityKey": "chinacota",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-cucuta",
    "label": "Cúcuta",
    "municipalityKey": "cucuta",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-carmen",
    "label": "El Carmen",
    "municipalityKey": "el carmen",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-tarra",
    "label": "El Tarra",
    "municipalityKey": "el tarra",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-zulia",
    "label": "El Zulia",
    "municipalityKey": "el zulia",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-labateca",
    "label": "Labateca",
    "municipalityKey": "labateca",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-ocana",
    "label": "Ocaña",
    "municipalityKey": "ocana",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-pamplona",
    "label": "Pamplona",
    "municipalityKey": "pamplona",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-puerto-santander",
    "label": "Puerto Santander",
    "municipalityKey": "puerto santander",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-san-calixto",
    "label": "San Calixto",
    "municipalityKey": "san calixto",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-sardinata",
    "label": "Sardinata",
    "municipalityKey": "sardinata",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-tibu",
    "label": "Tibú",
    "municipalityKey": "tibu",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-zulia",
    "label": "Zulia",
    "municipalityKey": "zulia",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-abrego",
    "label": "Ábrego",
    "municipalityKey": "abrego",
    "departmentKey": "norte de santander",
    "departmentLabel": "Norte de Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-mocoa",
    "label": "Mocoa",
    "municipalityKey": "mocoa",
    "departmentKey": "putumayo",
    "departmentLabel": "Putumayo",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-calarca",
    "label": "Calarcá",
    "municipalityKey": "calarca",
    "departmentKey": "quindio",
    "departmentLabel": "Quindío",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-irra",
    "label": "Irra",
    "municipalityKey": "irra",
    "departmentKey": "risaralda",
    "departmentLabel": "Risaralda",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-barrancabermeja",
    "label": "Barrancabermeja",
    "municipalityKey": "barrancabermeja",
    "departmentKey": "santander",
    "departmentLabel": "Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-bucaramanga",
    "label": "Bucaramanga",
    "municipalityKey": "bucaramanga",
    "departmentKey": "santander",
    "departmentLabel": "Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-curuti",
    "label": "Curutí",
    "municipalityKey": "curuti",
    "departmentKey": "santander",
    "departmentLabel": "Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-floridablanca",
    "label": "Floridablanca",
    "municipalityKey": "floridablanca",
    "departmentKey": "santander",
    "departmentLabel": "Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-lebrija",
    "label": "Lebrija",
    "municipalityKey": "lebrija",
    "departmentKey": "santander",
    "departmentLabel": "Santander",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-ataco",
    "label": "Ataco",
    "municipalityKey": "ataco",
    "departmentKey": "tolima",
    "departmentLabel": "Tolima",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-lerida",
    "label": "Lérida",
    "municipalityKey": "lerida",
    "departmentKey": "tolima",
    "departmentLabel": "Tolima",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-natagaima",
    "label": "Natagaima",
    "municipalityKey": "natagaima",
    "departmentKey": "tolima",
    "departmentLabel": "Tolima",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-buenaventura",
    "label": "Buenaventura",
    "municipalityKey": "buenaventura",
    "departmentKey": "valle del cauca",
    "departmentLabel": "Valle del Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-cali",
    "label": "Cali",
    "municipalityKey": "cali",
    "departmentKey": "valle del cauca",
    "departmentLabel": "Valle del Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-el-tambo",
    "label": "El Tambo",
    "municipalityKey": "el tambo",
    "departmentKey": "valle del cauca",
    "departmentLabel": "Valle del Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-jamundi",
    "label": "Jamundí",
    "municipalityKey": "jamundi",
    "departmentKey": "valle del cauca",
    "departmentLabel": "Valle del Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-palmira",
    "label": "Palmira",
    "municipalityKey": "palmira",
    "departmentKey": "valle del cauca",
    "departmentLabel": "Valle del Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-popayan",
    "label": "Popayán",
    "municipalityKey": "popayan",
    "departmentKey": "valle del cauca",
    "departmentLabel": "Valle del Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  },
  {
    "id": "muni-san-pedro",
    "label": "San Pedro",
    "municipalityKey": "san pedro",
    "departmentKey": "valle del cauca",
    "departmentLabel": "Valle del Cauca",
    "countryCode": "CO",
    "latitude": 4.57,
    "longitude": -75.5
  }
]

export const TERRITORY_PROJECTS: TerritoryProject[] = [
  {
    "id": "project-1502",
    "label": "Nueva Esperanza-La Virgnia",
    "noProyect": "1502",
    "countryCode": "CO",
    "latitude": 5.46606,
    "longitude": -75.63571,
    "departmentKeys": [
      "caldas"
    ]
  },
  {
    "id": "project-1693",
    "label": "COPA-Interconexión Eléctrica Colombia-Panamá",
    "noProyect": "1693",
    "countryCode": "CO",
    "latitude": 7.94256,
    "longitude": -75.91692,
    "departmentKeys": [
      "cordoba"
    ]
  },
  {
    "id": "project-1869",
    "label": "Parque Solar aires",
    "noProyect": "1869",
    "countryCode": "CO",
    "latitude": 8.79898,
    "longitude": -75.41947,
    "departmentKeys": [
      "cordoba"
    ]
  },
  {
    "id": "project-1876",
    "label": "Corredor de la soberanía (La Lejía-Saravena",
    "noProyect": "1876",
    "countryCode": "CO",
    "latitude": 7.08821,
    "longitude": -72.25091,
    "departmentKeys": [
      "arauca",
      "boyaca",
      "norte de santander"
    ]
  },
  {
    "id": "project-2046",
    "label": "Parque Fotovoltaico Atlántico",
    "noProyect": "2046",
    "countryCode": "CO",
    "latitude": 10.62532,
    "longitude": -74.95704,
    "departmentKeys": [
      "atlantico"
    ]
  },
  {
    "id": "project-2077",
    "label": "Emergias Renovables",
    "noProyect": "2077",
    "countryCode": "CO",
    "latitude": 10.60217,
    "longitude": -74.80324,
    "departmentKeys": [
      "atlantico"
    ]
  },
  {
    "id": "project-2104",
    "label": "Centro Regional de Pronosticos",
    "noProyect": "2104",
    "countryCode": "CO",
    "latitude": 4.10462,
    "longitude": -73.48849,
    "departmentKeys": [
      "meta"
    ]
  },
  {
    "id": "project-2199",
    "label": "Ingeniería APP Chirajara-25726232",
    "noProyect": "2199",
    "countryCode": "CO",
    "latitude": 4.10462,
    "longitude": -73.48849,
    "departmentKeys": [
      "meta"
    ]
  },
  {
    "id": "project-23635543",
    "label": "Embalse de Punchiná",
    "noProyect": "23635543",
    "countryCode": "CO",
    "latitude": 6.19402,
    "longitude": -74.9104,
    "departmentKeys": [
      "antioquia"
    ]
  },
  {
    "id": "project-23635730",
    "label": "EIA parque Solar La Achira de 60MW",
    "noProyect": "23635730",
    "countryCode": "CO",
    "latitude": 2.54862,
    "longitude": -75.44897,
    "departmentKeys": [
      "huila"
    ]
  },
  {
    "id": "project-23636695",
    "label": "LT SOLA-Línea de transmisión La Loma- Sogamoso",
    "noProyect": "23636695",
    "countryCode": "CO",
    "latitude": 8.30027,
    "longitude": -73.4939,
    "departmentKeys": [
      "cesar",
      "norte de santander",
      "santander"
    ]
  },
  {
    "id": "project-23663441",
    "label": "Subestación Betania",
    "noProyect": "23663441",
    "countryCode": "CO",
    "latitude": 2.63205,
    "longitude": -75.41228,
    "departmentKeys": [
      "huila"
    ]
  },
  {
    "id": "project-24675858",
    "label": "Arena Primavera",
    "noProyect": "24675858",
    "countryCode": "CO",
    "latitude": 6.13841,
    "longitude": -75.60838,
    "departmentKeys": [
      "antioquia"
    ]
  },
  {
    "id": "project-24700444",
    "label": "Proyecto 24700444",
    "noProyect": "24700444",
    "countryCode": "CO",
    "latitude": 4.29503,
    "longitude": -74.1958,
    "departmentKeys": [
      "cundinamarca"
    ]
  },
  {
    "id": "project-24718452",
    "label": "Verificacion mantenimiento de redes EPM",
    "noProyect": "24718452",
    "countryCode": "CO",
    "latitude": 7.1195,
    "longitude": -75.63957,
    "departmentKeys": [
      "antioquia"
    ]
  },
  {
    "id": "project-25726226",
    "label": "Eje vial Chia-Girardot",
    "noProyect": "25726226",
    "countryCode": "CO",
    "latitude": 4.59371,
    "longitude": -74.43174,
    "departmentKeys": [
      "cundinamarca"
    ]
  },
  {
    "id": "project-25726693",
    "label": "SPK LA UNION SAS",
    "noProyect": "25726693",
    "countryCode": "CO",
    "latitude": 8.59209,
    "longitude": -75.96231,
    "departmentKeys": [
      "cordoba"
    ]
  },
  {
    "id": "project-25729366",
    "label": "Ruta del Cacao",
    "noProyect": "25729366",
    "countryCode": "CO",
    "latitude": 7.02741,
    "longitude": -73.80142,
    "departmentKeys": [
      "santander"
    ]
  }
]

export const PROJECT_DEPARTMENT_KEYS: Record<string, string[]> = {
  "project-1502": [
    "caldas"
  ],
  "project-1693": [
    "cordoba"
  ],
  "project-1869": [
    "cordoba"
  ],
  "project-1876": [
    "arauca",
    "boyaca",
    "norte de santander"
  ],
  "project-2046": [
    "atlantico"
  ],
  "project-2077": [
    "atlantico"
  ],
  "project-2104": [
    "meta"
  ],
  "project-2199": [
    "meta"
  ],
  "project-23635543": [
    "antioquia"
  ],
  "project-23635730": [
    "huila"
  ],
  "project-23636695": [
    "cesar",
    "norte de santander",
    "santander"
  ],
  "project-23663441": [
    "huila"
  ],
  "project-24675858": [
    "antioquia"
  ],
  "project-24700444": [
    "cundinamarca"
  ],
  "project-24718452": [
    "antioquia"
  ],
  "project-25726226": [
    "cundinamarca"
  ],
  "project-25726693": [
    "cordoba"
  ],
  "project-25729366": [
    "santander"
  ]
}

export const DEPARTMENT_PRIMARY_PROJECT: Record<string, string> = {
  "caldas": "project-1502",
  "cordoba": "project-1693",
  "arauca": "project-1876",
  "boyaca": "project-1876",
  "norte de santander": "project-1876",
  "atlantico": "project-2046",
  "meta": "project-2104",
  "antioquia": "project-23635543",
  "huila": "project-23635730",
  "cesar": "project-23636695",
  "santander": "project-23636695",
  "cundinamarca": "project-24700444"
}
