from typing import Any

INCIDENTS: list[dict[str, Any]] = [
    {
        "id": "inc-001",
        "code": "SEG-001",
        "title": "Bloqueo total en vía hacia Sitio Alpha",
        "description": "Manifestación con cierre de calzada en corredor norte.",
        "type": "Bloqueo vial",
        "severity": "critical",
        "status": "open",
        "source": "Centro de monitoreo",
        "location": "Km 12 vía Planta–Alpha, sector Suba",
        "latitude": 4.735,
        "longitude": -74.095,
        "blocksTransit": True,
        "routeName": "Ruta Planta → Sitio Alpha",
        "targetWorkSite": "Sitio Alpha — Campo Norte",
        "reportedBy": "Coordinación de seguridad",
        "reportedAt": "2026-06-28T08:10:00Z",
        "updatedAt": "2026-06-28T08:10:00Z",
        "zoneId": "zone-norte",
        "zoneLabel": "Corredor Norte",
        "siteId": "site-alpha",
        "timeline": [],
    },
    {
        "id": "inc-002",
        "code": "SEG-002",
        "title": "Presencia de grupo armado en vía secundaria",
        "description": "Reporte de individuos armados en tramo alterno hacia Sitio Beta.",
        "type": "Presencia de grupo armado",
        "severity": "critical",
        "status": "in_review",
        "source": "Jefe de área",
        "location": "Desvío La Prosperidad, acceso a Sitio Beta",
        "latitude": 4.668,
        "longitude": -74.105,
        "blocksTransit": True,
        "routeName": "Ruta Planta → Sitio Beta",
        "targetWorkSite": "Sitio Beta — Corredor Central",
        "reportedBy": "Carlos Ruiz",
        "reportedAt": "2026-06-28T07:45:00Z",
        "updatedAt": "2026-06-28T09:00:00Z",
        "zoneId": "zone-centro",
        "zoneLabel": "Corredor Central",
        "siteId": "site-beta",
        "timeline": [],
    },
]
